INSERT INTO SEGURANCA.MODULO VALUES
('CADLOGIN', 'CADASTRO DE USUÁRIOS',1),
('CADFUNC', 'CADASTRO DE FUNCIONALIDADES',1),
('CADGRPS', 'CADASTRO DE GRUPOS DE USUÁRIOS',1),
('CADMOD', 'CADASTRO DE MÓDULOS',1);